import AppKit

/// Clipboard history (CopyClip-style) shown in the island's Clipboard tab.
/// Kept in ~/Library/Application Support/Coucou/Clipboard: an index JSON plus one PNG per image.
@MainActor
final class ClipboardStore: ObservableObject {
    static let shared = ClipboardStore()
    static let maxItems = 200   // unpinned; pinned items are never evicted

    enum Kind: String, Codable { case text, link, color, image, file }

    struct Item: Codable, Identifiable, Equatable {
        var id = UUID()
        var kind: Kind
        var text: String          // text / URL / hex / file paths (newline-separated) / image label
        var appBundleId: String?
        var date = Date()
        var pinned = false
    }

    @Published private(set) var items: [Item] = []
    /// Bumped when an item is copied back, so the view can flash + Mochi can react.
    @Published private(set) var lastCopied: UUID?

    private var changeCount = NSPasteboard.general.changeCount
    private var timer: Timer?
    private let dir: URL = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        .appendingPathComponent("Coucou/Clipboard", isDirectory: true)
    private var indexURL: URL { dir.appendingPathComponent("index.json") }

    // Password managers mark their copies with these (nspasteboard.org); never stored.
    private static let skipped: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
    ]

    func start() {
        guard timer == nil else { return }
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        if let data = try? Data(contentsOf: indexURL),
           let saved = try? JSONDecoder().decode([Item].self, from: data) { items = saved }
        // ponytail: macOS has no pasteboard-change notification, so poll changeCount (an int read)
        // twice a second like CopyClip/Maccy. Not 0 % CPU when hidden; there is no event to wait on.
        let t = Timer(timeInterval: 0.5, repeats: true) { _ in
            MainActor.assumeIsolated { ClipboardStore.shared.poll() }
        }
        t.tolerance = 0.25
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != changeCount else { return }
        changeCount = pb.changeCount
        let types = Set((pb.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.skipped) else { return }
        let app = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        guard app != Bundle.main.bundleIdentifier else { return }

        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            add(Item(kind: .file, text: urls.map(\.path).joined(separator: "\n"), appBundleId: app))
        } else if let image = NSImage(pasteboard: pb), pb.string(forType: .string) == nil {
            let item = Item(kind: .image, text: "Image \(Int(image.size.width))×\(Int(image.size.height))", appBundleId: app)
            guard let png = image.pngData() else { return }
            try? png.write(to: imageURL(item.id))
            add(item)
        } else if let s = pb.string(forType: .string), !s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            add(Item(kind: Self.kind(of: s), text: s, appBundleId: app))
        }
    }

    static func kind(of s: String) -> Kind {
        let t = s.trimmingCharacters(in: .whitespacesAndNewlines)
        if !t.contains(" "), !t.contains("\n"), let u = URL(string: t), let scheme = u.scheme,
           ["http", "https"].contains(scheme.lowercased()), u.host != nil { return .link }
        if t.range(of: "^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})$", options: .regularExpression) != nil { return .color }
        return .text
    }

    private func add(_ item: Item) {
        // Same content copied again: move it to the front (keeping its pin).
        var item = item
        if item.kind != .image, let i = items.firstIndex(where: { $0.kind == item.kind && $0.text == item.text }) {
            item.id = items[i].id
            item.pinned = items[i].pinned
            items.remove(at: i)
        }
        items.insert(item, at: 0)
        var unpinned = 0
        items = items.filter { $0.pinned || { unpinned += 1; return unpinned <= Self.maxItems }() }
        save()
    }

    // MARK: - Actions

    func copy(_ item: Item) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch item.kind {
        case .image:
            if let img = image(for: item) { pb.writeObjects([img]) }
        case .file:
            pb.writeObjects(item.text.split(separator: "\n").map { URL(fileURLWithPath: String($0)) as NSURL })
        default:
            pb.setString(item.text, forType: .string)
        }
        changeCount = pb.changeCount   // our own write is not a new entry
        if let i = items.firstIndex(of: item) {
            var moved = items.remove(at: i)
            moved.date = Date()
            items.insert(moved, at: 0)
            save()
        }
        lastCopied = item.id
    }

    func togglePin(_ item: Item) {
        guard let i = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[i].pinned.toggle()
        save()
    }

    func delete(_ item: Item) {
        items.removeAll { $0.id == item.id }
        if item.kind == .image { try? FileManager.default.removeItem(at: imageURL(item.id)) }
        save()
    }

    func clearUnpinned() {
        for item in items where !item.pinned && item.kind == .image {
            try? FileManager.default.removeItem(at: imageURL(item.id))
        }
        items.removeAll { !$0.pinned }
        save()
    }

    // MARK: - Storage

    func imageURL(_ id: UUID) -> URL { dir.appendingPathComponent("\(id.uuidString).png") }

    func image(for item: Item) -> NSImage? { NSImage(contentsOf: imageURL(item.id)) }

    private let thumbs = NSCache<NSUUID, NSImage>()
    func thumbnail(for item: Item) -> NSImage? {
        if let t = thumbs.object(forKey: item.id as NSUUID) { return t }
        guard let img = image(for: item) else { return nil }
        thumbs.setObject(img, forKey: item.id as NSUUID)
        return img
    }

    private func save() {
        let live = Set(items.filter { $0.kind == .image }.map { "\($0.id.uuidString).png" })
        for f in (try? FileManager.default.contentsOfDirectory(atPath: dir.path)) ?? []
        where f.hasSuffix(".png") && !live.contains(f) {
            try? FileManager.default.removeItem(at: dir.appendingPathComponent(f))
        }
        if let data = try? JSONEncoder().encode(items) { try? data.write(to: indexURL, options: .atomic) }
    }
}

private extension NSImage {
    func pngData() -> Data? {
        guard let tiff = tiffRepresentation, let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }
}
